Feature/survey email
UUDigitalHumanitieslab/coloringbook pull request #29
Opened 2023-12-20 14:48 UTC by XanderVertegaal

This PR enables the user to add an email address when creating/editing a survey. When results from the survey are uploaded to the server, an email is sent out asynchronously to the provided address. The email looks like this.

![image](https://github.com/UUDigitalHumanitieslab/coloringbook/assets/73882506/097507e6-7236-4124-abd9-7fc259a89752)

Changes:
- A column `email_address` has been added to the `survey` table, and a migration has been written accordingly.
- The survey form is updated with an `email address` field, with validation and a description.
- The application and its database have been dockerized and combined in a Docker Compose network.
- Celery and Redis are added for async email handling.
- The README has been updated, documenting the new Docker approach.

NB: the SMTP server is not reachable from anywhere else but the server network. Therefore, sending emails will be difficult to test until we actually deploy to a test server.

2024-01-09 23:02 UTC, jgonggrijp requested changes
After one hiccup, which I was able to solve quickly without help, `docker compose` ran smoothly and everything seems to work. Kudos on that!

This branch, PR and review combine two independent sets of changes: those pertaining to Dockerized deployment and those pertaining to emailing the survey results. I understand why you did it this way in this case, but generally, I would prefer that you submit two indepent PRs where neither contains changes related to the other. We can discuss the git-fu that makes this possible, if you like.

> NB: the SMTP server is not reachable from anywhere else but the server network. Therefore, sending emails will be difficult to test until we actually deploy to a test server.

The Flask-Mail documentation [discusses a way](https://pythonhosted.org/Flask-Mail/#unit-tests-and-suppressing-emails) in which emails can be intercepted in debug mode, so you can log them instead of sending them and/or check their contents in a unittest. Please explore this option; it would be reassuring to have a way to check that this feature works as intended, without having to deploy it.

The existing tests are based on [doctest](https://docs.python.org/3/library/doctest.html). You can see an example of an existing test in `coloringbook/utilities.py:subject_from_json`, lines 28-53. That particular test will currently not run, because you still need to add `coloringbook/utilities.py` to the `test.py`. Try `python test.py` once you have done that, then try writing your own test for `is_fill_correct` as a warmup exercise. With that and the Flask-Mail documentation, I think you should be able to write some test code for the email feature as well.

Apart from the comments above and below, the code changes look perfectly sensible to me. :+1:

2024-01-11 09:55 UTC, XanderVertegaal commented on coloringbook/admin/utilities.py
> +# coding=utf-8
I'm afraid so. My container does not run without it, in any case.

![image](https://github.com/UUDigitalHumanitieslab/coloringbook/assets/73882506/16375137-f4a5-421c-811a-083121211bb6)

(The character denoted with \xc3 is ã, apparently.)

2024-01-11 10:14 UTC, XanderVertegaal commented
I'm glad to hear you got the docker containers up and running!

Your comments on splitting this branch and writing tests are taken to heart. I will close this PR, cherry pick the commits from this branch onto two new separate branches and open PRs for them. Your other comments will be addressed there as well.

2024-01-11 10:14 UTC, closed without merging

2024-01-11 12:44 UTC, XanderVertegaal commented on Readme.md
> +Secondly, a file `CONFIG.py` is required with minimally the following contents
The capitalization in CONFIG.py (in the previous PR) was based on my misreading of the README, which used all-caps "CONFIG" as a placeholder for 'the actual name of the config file'. There is no reason why the name of the configuration file should be in all caps. It has been fixed in the new PR.

2024-01-11 12:46 UTC, XanderVertegaal commented on .gitignore
> +/coloringbook/config.py
Lowercase is now used throughout (as it should be).

2024-01-11 12:48 UTC, XanderVertegaal commented on Readme.md
> +Coloring Book is deployed using Docker Compose. The application needs two configuration files, which must be present in the same folder as `docker-compose.yml`.
This was confusing indeed. I have corrected this in the new PR.

2024-01-11 12:51 UTC, XanderVertegaal commented on coloringbook/admin/utilities.py
> +# coding=utf-8
This magic comment appears to be necessary. My container will not run without it.

![image](https://github.com/UUDigitalHumanitieslab/coloringbook/assets/73882506/16375137-f4a5-421c-811a-083121211bb6)

(The character denoted with \xc3 is ã, apparently.)

2024-01-11 13:16 UTC, XanderVertegaal commented on migrations/alembic.ini
> +script_location = %(here)s
I cannot create a migration without them. I have looked at this again, and the only required line is `script_location = %(here)s`; the other lines can be left as is. (I do not know what they do exactly.)

2024-01-11 13:31 UTC, XanderVertegaal commented on coloringbook/templates/email/email.html
> +            <tr>Er zijn geen resultaten geregistreerd.</tr>
Toen ik het testte, zag het er goed uit, maar het kan inderdaad netter:

```
        {% else %}
            <tr>
                <td colspan="3">Er zijn geen resultaten geregistreerd.</td>
            </tr>
        {% endfor %}
```

2024-01-11 13:50 UTC, XanderVertegaal commented on coloringbook/templates/email/email.html
> +<p>Het Coloring Bookteam</p>
Not really; good spot!